CREATE TABLE IF NOT EXISTS users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 username VARCHAR(100) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role VARCHAR(20) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS master (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 category VARCHAR(40) NOT NULL,
 code VARCHAR(100) NOT NULL,
 label VARCHAR(255) NOT NULL,
 parent_code VARCHAR(100) NOT NULL DEFAULT '',
 UNIQUE KEY master_key(category,code)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS assessments (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 identity_key CHAR(64) NOT NULL UNIQUE,
 nik VARCHAR(16) NOT NULL,
 name VARCHAR(255) NOT NULL,
 scheme VARCHAR(100) NOT NULL,
 registration VARCHAR(191) NULL,
 certificate VARCHAR(191) NULL UNIQUE,
 test_date VARCHAR(10) NOT NULL DEFAULT '',
 result VARCHAR(2) NOT NULL DEFAULT '',
 fields JSON NOT NULL,
 source VARCHAR(255) NOT NULL DEFAULT '',
 version INT NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY registration_scheme(scheme,registration),
 INDEX idx_nik(nik), INDEX idx_name(name), INDEX idx_date(test_date)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS documents (
 id CHAR(32) PRIMARY KEY,
 assessment_id BIGINT NOT NULL,
 name VARCHAR(255) NOT NULL,
 category VARCHAR(40) NOT NULL,
 mime VARCHAR(100) NOT NULL,
 size BIGINT NOT NULL,
 sha256 CHAR(64) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (assessment_id) REFERENCES assessments(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 username VARCHAR(100) NOT NULL,
 action VARCHAR(60) NOT NULL,
 detail TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS registerweb_snapshot (
 id INT PRIMARY KEY,
 catalog JSON NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS registration_sequences (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 scheme VARCHAR(100) NOT NULL,
 year INT NOT NULL,
 last_seq BIGINT NOT NULL DEFAULT 0,
 UNIQUE KEY scheme_year(scheme,year)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS certificate_sequences (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 scheme VARCHAR(100) NOT NULL DEFAULT '0',
 year INT NOT NULL,
 last_seq BIGINT NOT NULL DEFAULT 0,
 UNIQUE KEY scheme_year(scheme,year)
) ENGINE=InnoDB;
