'use strict';
const $ = (selector, root = document) => root.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state = {user:null, meta:null, records:[], all:[], page:1, preview:null, previewPage:1, selected:new Set(), filters:{q:'',scheme:'',result:'',year:''}, detail:null, docs:[], tab:'data', masterCategory:'SKEMA', masterSort:{column:'code',order:'asc'}, masterSearch:''};
const names = {dashboard:'Ringkasan',records:'Data asesmen',import:'Impor data',masters:'Data referensi',registerweb:'Database RegisterWeb',registrations:'Registrasi & sertifikat',activity:'Riwayat aktivitas',settings:'Pengaturan'};
const isAdmin = () => state.user?.role === 'admin';
const badge = value => value === 'K' ? '<span class="badge green">● Kompeten</span>' : value === 'BK' ? '<span class="badge orange">● Belum kompeten</span>' : '<span class="badge">Belum tercatat</span>';
const number = n => new Intl.NumberFormat('id-ID').format(n);
const date = s => s ? new Date(s+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}) : '—';
const schemeName = code => state.meta?.masters.find(m => m.category === 'SKEMA' && m.code === code)?.label || code || '—';
const admin = html => isAdmin() ? html : '';
let toastTimer;
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.add('hidden'),6500);}
async function download(path){const res=await fetch(path);if(!res.ok){const data=await res.json();throw new Error(data.error||'Unduhan gagal.');}const blob=await res.blob();const link=document.createElement('a');const url=URL.createObjectURL(blob);link.href=url;link.download=res.headers.get('Content-Disposition')?.match(/filename="([^"]+)"/)?.[1]||'LSPFI-unduhan';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function showLogin(){state.user=null;state.meta=null;state.records=[];state.all=[];state.preview=null;state.detail=null;state.docs=[];$('#detail-dialog').close();$('#content').replaceChildren();$('#detail-content').replaceChildren();$('#app-view').classList.add('hidden');$('#login-view').classList.remove('hidden');$('#login-form').reset();}
function releasePreviewImage(){const viewer=$('#doc-viewer');if(viewer?.dataset.blob)URL.revokeObjectURL(viewer.dataset.blob);}
async function start(){state.meta=await api('/api/meta');$('#login-view').classList.add('hidden');$('#app-view').classList.remove('hidden');$('#user-name').textContent=state.user.username;$('#user-role').textContent=isAdmin()?'Administrator':'Pembaca arsip';$('#user-avatar').textContent=state.user.username[0].toUpperCase();document.querySelectorAll('.admin-only').forEach(el=>el.classList.toggle('hidden',!isAdmin()));$('#today').textContent=new Date().toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'});await route();}
function heading(title,description,actions=''){return `<div class="page-heading"><div><h1>${title}</h1><p>${description}</p></div><div class="actions">${actions}</div></div>`;}
function empty(title,description,action=''){return `<div class="empty"><div class="empty-symbol">▤</div><h3>${title}</h3><p>${description}</p>${action}</div>`;}
function table(rows){if(!rows.length)return empty('Belum ada data asesmen','Impor Data Induk Asesi atau tambahkan data untuk mulai menyusun arsip digital.',admin('<a class="button primary" href="#import">↥ Impor data pertama</a>'));return `<div class="table-wrap"><table><thead><tr><th>Asesi</th><th>Skema sertifikasi</th><th>Tanggal uji</th><th>Hasil asesmen</th><th>Dokumen</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><div class="person"><span class="avatar">${esc(r.fields.name[0]?.toUpperCase()||'?')}</span><div><strong>${esc(r.fields.name)}</strong><small>${esc(r.fields.nik)}</small></div></div></td><td><strong>${esc(schemeName(r.fields.scheme))}</strong><small>${esc(r.fields.registration||'Nomor belum tercatat')}</small></td><td>${date(r.fields.test_date)}</td><td>${badge(r.fields.result)}</td><td><span class="badge ${r.documents?'green':''}">▧ ${number(r.documents)} berkas</span></td><td><button class="row-button" data-action="detail" data-id="${r.id}">Lihat detail ↗</button></td></tr>`).join('')}</tbody></table></div>`;}
let routeSerial=0;
async function route(){if(!state.user)return;const routeID=++routeSerial;let view=location.hash.slice(1)||'dashboard';if(!names[view])view='dashboard';if(!isAdmin()&&['import','activity','registerweb','registrations'].includes(view))view='dashboard';document.querySelectorAll('[data-nav]').forEach(el=>el.classList.toggle('active',el.dataset.nav===view));$('#breadcrumb').textContent=names[view];$('#content').innerHTML='<div class="loading">Memuat ruang arsip…</div>';try{if(view==='dashboard'||view==='records'){const rows=await api('/api/records');if(routeID!==routeSerial)return;state.all=rows;if(view==='dashboard')renderDashboard();else{state.page=1;renderRecords();}}else if(view==='import')renderImport();else if(view==='masters'){state.meta=await api('/api/meta');if(routeID===routeSerial)renderMasters();}else if(view==='registrations'){const data=await api('/api/registrations');const rows=await api('/api/records');if(routeID===routeSerial){state.all=rows;renderRegistrations(data);}}else if(view==='registerweb'){await showRegisterWeb();}else if(view==='activity'){const rows=await api('/api/audit');if(routeID===routeSerial)renderActivity(rows);}else renderSettings();}catch(e){if(routeID===routeSerial)$('#content').innerHTML=empty('Data belum dapat dimuat',esc(e.message),'<button data-action="reload">Coba lagi</button>');}}
function renderDashboard(){const rows=state.all;const complete=rows.filter(r=>r.documents>0).length;const stats=[['Total asesmen',rows.length,'Seluruh riwayat yang tersimpan','▤'],['Asesi unik',new Set(rows.map(r=>r.fields.nik)).size,'Dikelompokkan berdasarkan NIK','♙'],['Memiliki scan',complete,'Asesmen dengan berkas digital','▧'],['Belum ada scan',rows.length-complete,'Menunggu unggahan dokumen','◷']];$('#content').innerHTML=heading('Ringkasan arsip','Kelola riwayat asesmen dan temukan dokumen yang Anda butuhkan.',admin('<button data-action="new">＋ Tambah asesmen</button><a class="button primary" href="#import">↥ Impor Excel</a>'))+`<div class="stats">${stats.map(s=>`<div class="stat"><div class="stat-top">${s[0]}<span class="stat-icon">${s[3]}</span></div><strong>${number(s[1])}</strong><small>${s[2]}</small></div>`).join('')}</div><div class="welcome-card"><div><span class="eyebrow teal">ARSIP YANG TERHUBUNG</span><h2>Dari lembar kerja menjadi riwayat yang utuh.</h2><p>Hubungkan Data Induk Asesi dengan scan APL, rekaman asesmen, dan sertifikat. Cari berdasarkan nama, NIK, atau nomor registrasi dalam satu ruang kerja.</p></div><div class="welcome-mark">▤</div></div><section class="panel"><div class="panel-title"><div><h2>Asesmen terbaru</h2><p>Data yang terakhir ditambahkan ke ruang arsip</p></div><a href="#records">Lihat semua asesmen →</a></div>${table(rows.slice(0,5))}</section><div class="two-col"><div class="panel"><div class="panel-body"><span class="eyebrow teal">01 / MULAI DARI DATA INDUK</span><h3 class="section-label">EXCEL → TINJAU → SIMPAN</h3><p class="helper">Impor format 32 kolom dari RegisterWeb Dashboard. Sistem memeriksa identitas, kode referensi, tanggal, dan data ganda sebelum penyimpanan.</p>${admin('<a class="text-link" href="#import">Buka halaman impor →</a>')}</div></div><div class="panel"><div class="panel-body"><span class="eyebrow teal">02 / JAGA SALINAN ARSIP</span><h3 class="section-label">CADANGAN REFERENSI TANPA DATA ASESI</h3><p class="helper">Cadangkan master, perangkat asesmen, dan akun pengelola tanpa menyertakan data pribadi asesi. Simpan ZIP di hard drive lain atau Google Drive milik LSPFI.</p><a class="text-link" href="#settings">Pengaturan penyimpanan →</a></div></div></div>`;}
function filtered(){const f=state.filters;const q=f.q.toLocaleLowerCase('id');return state.all.filter(r=>(!q||['name','nik','registration','certificate','company'].some(k=>(r.fields[k]||'').toLocaleLowerCase('id').includes(q)))&&(!f.scheme||r.fields.scheme===f.scheme)&&(!f.result||(f.result==='pending'?!r.fields.result:r.fields.result===f.result))&&(!f.year||r.fields.test_date.startsWith(f.year)));}
function renderRecords(){const f=state.filters;const years=[...new Set(state.all.map(r=>r.fields.test_date.slice(0,4)).filter(Boolean))].sort().reverse();$('#content').innerHTML=heading('Data asesmen','Satu asesi dapat memiliki beberapa riwayat asesmen dan skema.',`<button data-action="export">↓ Ekspor Excel</button>${admin('<button class="primary" data-action="new">＋ Tambah asesmen</button>')}`)+`<section class="panel"><div class="toolbar"><input id="record-search" aria-label="Cari asesmen" placeholder="Cari nama, NIK, registrasi, sertifikat, atau perusahaan…" value="${esc(f.q)}"><select id="filter-scheme" aria-label="Filter skema">${options('SKEMA',f.scheme,'Semua skema')}</select><select id="filter-year" aria-label="Filter tahun"><option value="">Semua tahun</option>${years.map(y=>`<option ${f.year===y?'selected':''}>${y}</option>`).join('')}</select><select id="filter-result" aria-label="Filter hasil"><option value="">Semua hasil</option><option value="K" ${f.result==='K'?'selected':''}>Kompeten</option><option value="BK" ${f.result==='BK'?'selected':''}>Belum kompeten</option><option value="pending" ${f.result==='pending'?'selected':''}>Belum tercatat</option></select></div><div id="record-table"></div></section>`;renderRecordTable();}
function renderRecordTable(){state.records=filtered();const pages=Math.max(1,Math.ceil(state.records.length/20));state.page=Math.min(pages,state.page);$('#record-table').innerHTML=(state.records.length?table(state.records.slice((state.page-1)*20,state.page*20)):empty(state.all.length?'Tidak ada hasil yang sesuai':'Belum ada data asesmen',state.all.length?'Coba kata kunci lain atau ubah filter pencarian.':'Mulai dengan mengimpor Excel atau menambahkan asesmen.'))+`<div class="pagination"><span>${number(state.records.length)} asesmen ditemukan</span><div class="actions"><span>Halaman ${state.page} dari ${pages}</span><button data-action="page" data-delta="-1" ${state.page===1?'disabled':''}>←</button><button data-action="page" data-delta="1" ${state.page===pages?'disabled':''}>→</button></div></div>`;}
function renderImport(){const p=state.preview;$('#content').innerHTML=heading('Impor Data Induk Asesi','Pindahkan data dari Excel, periksa hasilnya, lalu simpan ke arsip.','<button data-action="template">↓ Unduh template</button>')+`<div class="steps"><span><b>1</b>Pilih file Excel</span><span>→</span><span><b>2</b>Tinjau hasil pemeriksaan</span><span>→</span><span><b>3</b>Simpan baris pilihan</span></div><div class="two-col"><section class="panel"><div class="panel-title"><h2>Unggah lembar kerja</h2><span class="chip">.XLSX / .CSV</span></div><div class="panel-body"><form id="import-form"><div class="upload-zone"><div class="empty-symbol">↥</div><h3>Mulai dari file Data Induk</h3><p>File sumber disimpan setelah impor berhasil.<br>Maksimal 20 MB dan 10.000 baris per impor.</p><input type="file" name="file" accept=".xlsx,.csv" required aria-label="File Data Induk"></div><label>Nama sheet (opsional)<input name="sheet" placeholder="Otomatis memilih sheet Data Induk"></label><button class="primary" type="submit">Periksa file →</button></form></div></section><section class="panel"><div class="panel-title"><h2>Sebelum mengimpor</h2></div><div class="panel-body"><ul class="plain-list"><li>NIK harus 16 digit, dengan format sel <strong>Text</strong>.</li><li>Isi nama, tanggal lahir, email, telepon, dan skema.</li><li>Sertakan nomor registrasi atau tanggal uji.</li><li>Kode pendidikan dan pekerjaan mengikuti master.</li><li>Hasil asesmen: K, BK, atau kosong jika belum diketahui.</li><li>Gunakan dd/mm/yyyy untuk tanggal.</li></ul><div class="info-box"><strong>Riwayat lama tetap dipertahankan</strong>Nomor sertifikat tidak dibuat otomatis. Duplikat akan ditandai dan tidak menimpa asesmen yang sudah tersimpan.</div></div></section></div><div id="import-preview"></div>`;if(p)renderPreview();}
function renderPreview(){const p=state.preview;if(!p)return;const pages=Math.max(1,Math.ceil(p.rows.length/50));const rows=p.rows.slice((state.previewPage-1)*50,state.previewPage*50);$('#import-preview').innerHTML=`<section class="panel"><div class="panel-title"><div><h2>Tinjauan impor · ${esc(p.filename)}</h2><p>Sheet: ${esc(p.sheet)} · Sheet tersedia: ${p.sheets.map(esc).join(', ')} · Untuk mengganti sheet, periksa file kembali.</p></div></div>${p.unknown.length?`<div class="info-box"><strong>Kolom tambahan tidak masuk ke data terstruktur</strong>${p.unknown.map(esc).join(', ')}. Nilai asli tetap tersedia dalam file sumber setelah impor berhasil; file ini tidak termasuk cadangan referensi.</div>`:''}<div class="summary-bar"><span><strong>${number(p.valid)}</strong> valid · <strong>${number(p.rows.length-p.valid)}</strong> perlu perbaikan · <strong id="selected-count">${state.selected.size}</strong> dipilih</span><button class="primary" data-action="commit" ${!state.selected.size?'disabled':''}>Simpan baris pilihan →</button></div><div class="table-wrap"><table><thead><tr><th><input type="checkbox" class="check" id="select-valid" aria-label="Pilih semua baris valid" ${state.selected.size===p.valid&&p.valid?'checked':''}></th><th>Baris</th><th>Nama / NIK</th><th>Skema</th><th>Hasil pemeriksaan</th></tr></thead><tbody>${rows.map(row=>`<tr><td><input type="checkbox" class="check" data-row="${row.number}" aria-label="Pilih baris ${row.number}" ${state.selected.has(row.number)?'checked':''} ${row.errors.length?'disabled':''}></td><td>${row.number}</td><td><strong>${esc(row.fields.name)}</strong><small>${esc(row.fields.nik)}</small></td><td>${esc(schemeName(row.fields.scheme))}</td><td class="preview-errors">${row.errors.length?row.errors.map(esc).join('<br>'):'<span class="badge green">✓ Siap disimpan</span>'}</td></tr>`).join('')}</tbody></table></div><div class="pagination"><span>${number(p.rows.length)} baris · Pilihan berlaku untuk seluruh halaman</span><div class="actions"><span>${state.previewPage} / ${pages}</span><button data-action="preview-page" data-delta="-1" ${state.previewPage===1?'disabled':''}>←</button><button data-action="preview-page" data-delta="1" ${state.previewPage===pages?'disabled':''}>→</button></div></div></section>`;}
async function openDetail(id){state.meta=await api('/api/meta');state.detail=id?structuredClone(state.all.find(r=>r.id===Number(id))):{id:0,version:0,generate_registration:true,generate_certificate:true,fields:{}};if(!state.detail)throw new Error('Data berubah. Muat ulang halaman.');state.docs=state.detail.id?await api(`/api/records/${state.detail.id}/documents`):[];state.tab='data';renderDetail();$('#detail-dialog').showModal();}
function formField(field){const value=state.detail.fields[field.key]||'';const isAuto=(field.key==='registration'&&state.detail.generate_registration)||(field.key==='certificate'&&state.detail.generate_certificate);const disabled=!isAdmin()?'disabled':isAuto?'readonly':'';const required=['nik','name','birth_date','phone','email','scheme'].includes(field.key);let control='';if(field.kind==='master')control=`<select name="${field.key}" ${disabled} ${required?'required':''}>${assessmentOptions(field,value)}</select>`;else if(field.kind==='result')control=`<select name="${field.key}" ${disabled}><option value="">Belum tercatat</option><option value="K" ${value==='K'?'selected':''}>K · Kompeten</option><option value="BK" ${value==='BK'?'selected':''}>BK · Belum kompeten</option></select>`;else control=`<input name="${field.key}" type="${field.kind==='date'?'date':field.kind==='email'?'email':'text'}" value="${esc(value)}" ${disabled} ${required?'required':''} ${isAuto?'placeholder="Dibuat saat disimpan"':''} ${field.key==='nik'?'pattern="[0-9]{16}" maxlength="16" inputmode="numeric"':''} ${field.key==='name'?'maxlength="255"':'maxlength="1000"'}>`;return `<label>${esc(field.label)}${required?' *':''}${control}</label>`;}
function renderDetail(){releasePreviewImage();const r=state.detail;const groups=[['Identitas asesi',['name','nik','birth_place','birth_date','gender','address','province','city','phone','email','company','education','occupation']],['Riwayat asesmen',['scheme','registration','test_date','tuk','result','assessor','assessor_registration','schedule','funding','ministry']],['Sertifikasi',['certificate','blanko','met_year','plenary_date']]];$('#detail-content').innerHTML=`<div class="dialog-top"><div><h2>${esc(r.id?r.fields.name:'Tambah asesmen')}</h2><p>${r.id?`Arsip #${r.id} · ${esc(r.fields.nik)} · ${esc(schemeName(r.fields.scheme))}`:'Catat riwayat asesmen dari dokumen sumber'}</p></div><button data-action="close" aria-label="Tutup detail">✕</button></div><div class="tabs"><button class="${state.tab==='data'?'active':''}" data-action="detail-tab" data-tab="data">Data asesmen</button><button class="${state.tab==='docs'?'active':''}" data-action="detail-tab" data-tab="docs" ${!r.id?'disabled':''}>Dokumen scan (${state.docs.length})</button></div><div class="dialog-body">${state.tab==='data'?`<form id="record-form">${registrationControls(r)}<div class="form-grid">${groups.map(([title,keys])=>`<div class="section-label">${title.toUpperCase()}</div>${keys.map(k=>formField(state.meta.fields.find(f=>f.key===k))).join('')}`).join('')}</div><div class="info-box">Isi keputusan K/BK sesuai rekaman asesmen yang telah diperiksa. Jumlah scan tidak menunjukkan kelengkapan atau keabsahan asesmen.</div><p class="helper">${esc(r.source||'Sumber: input manual')}${r.updated?'<br>Diperbarui: '+esc(r.updated):''}</p><p id="record-error" class="error" role="alert"></p>${admin('<button class="primary" type="submit">Simpan data asesmen</button>')}</form>`:renderDocuments()}</div>`;}
function renderDocuments(){return `${admin(`<form id="document-form"><div class="form-grid"><label>Jenis dokumen<select name="category">${['KTP','FR.APL.01','FR.APL.02','FR.AK.02','FR.IA','SERTIFIKAT','IJAZAH','PORTOFOLIO','LAINNYA'].map(v=>`<option>${v}</option>`).join('')}</select></label><label>File scan · PDF, JPG, PNG · maksimal 20 MB<input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png" required></label></div><button class="primary" type="submit">↥ Simpan scan</button></form><div class="section-label">DOKUMEN TERSIMPAN</div>`)}`+(state.docs.length?state.docs.map(d=>`<div class="doc-item"><div><strong>${esc(d.name)}</strong><small>${esc(d.category)} · ${number(Math.ceil(d.size/1024))} KB · ${esc(d.created)}</small></div><div class="actions"><button data-action="view-doc" data-id="${d.id}">Lihat scan ↗</button><button data-action="download-doc" data-id="${d.id}">↓ Unduh</button></div></div>`).join(''):empty('Belum ada scan','Unggah dokumen agar bukti fisik dapat diakses kembali dari halaman ini.'))+'<div id="doc-viewer"></div>';}
function renderActivity(rows){$('#content').innerHTML=heading('Riwayat aktivitas','200 aktivitas terbaru untuk menelusuri perubahan pada ruang arsip.')+`<section class="panel"><div class="table-wrap"><table><thead><tr><th>Waktu</th><th>Pengguna</th><th>Aktivitas</th><th>Keterangan</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.username)}</td><td><span class="activity-dot"></span>${esc(r.action)}</td><td>${esc(r.detail)}</td></tr>`).join('')}</tbody></table>${rows.length?'':empty('Belum ada aktivitas','Perubahan data, unggahan scan, dan cadangan akan tercatat di sini.')}</div></section>`;}
function renderSettings(){$('#content').innerHTML=heading('Pengaturan','Kelola akses dan salinan cadangan arsip LSPFI.')+`<div class="two-col"><section class="panel"><div class="panel-title"><h2>Penyimpanan & cadangan</h2><span class="badge green">● Lokal</span></div><div class="panel-body"><label>Database MySQL</label><p class="storage-path">${esc(state.meta.database)}</p><label>Folder arsip</label><p class="storage-path">${esc(state.meta.storage)}</p><p class="helper">Data asesmen dan referensi tersimpan di MySQL. Scan dan file Excel sumber tersimpan di folder arsip.</p>${admin('<button class="primary" data-action="backup">↓ Cadangan tanpa data asesi (.zip)</button>')}<div class="info-box"><strong>Salinan ke Google Drive</strong>Unggah cadangan ZIP yang sudah selesai diunduh ke folder Google Drive LSPFI, atau salin ke hard drive lain. Sinkronisasi akun Drive otomatis belum diaktifkan.</div><p class="helper">Cadangan berisi master, skema, unit, elemen, KUK, bank/paket soal, parameter, penomoran, dan akun pengelola/asesor. Identitas serta akun asesi, pendaftaran, hasil asesmen, scan, Excel sumber, dan riwayat aktivitas tidak disertakan. Pemulihan ke database kosong mengikuti README.</p></div></section><section class="panel"><div class="panel-title"><h2>Ganti kata sandi</h2></div><div class="panel-body"><form id="password-form"><label>Kata sandi saat ini<input type="password" name="current" required autocomplete="current-password"></label><label>Kata sandi baru<input type="password" name="password" required minlength="12" maxlength="72" autocomplete="new-password"></label><p class="helper">Minimal 12 karakter. Seluruh sesi akun akan keluar setelah perubahan.</p><button class="primary" type="submit">Perbarui kata sandi</button></form></div></section></div>${admin(`<section class="panel"><div class="panel-title"><h2>Tambah akun pengguna</h2></div><div class="panel-body"><form id="user-form"><div class="form-grid"><label>Nama pengguna<input name="username" required minlength="3" maxlength="100" autocomplete="off"></label><label>Peran<select name="role"><option value="viewer">Pembaca · lihat dan ekspor seluruh arsip</option><option value="admin">Admin · kelola seluruh arsip</option></select></label><label>Kata sandi awal<input name="password" type="password" required minlength="12" maxlength="72" autocomplete="new-password"></label></div><p class="helper">Akun pembaca dapat mengakses seluruh arsip LSPFI. Akses klien yang dibatasi per asesi belum tersedia pada versi lokal ini.</p><button class="primary" type="submit">Buat akun</button></form></div></section>`)}`;}
document.addEventListener('input',event=>{
 if(event.target.id==='record-search'){state.filters.q=event.target.value;state.page=1;renderRecordTable();}
 if(event.target.id==='master-search'){state.masterSearch=event.target.value;state.masterPage=1;renderMasterTable();}
});
document.addEventListener('change',event=>{const el=event.target;if(el.id==='registration-auto'||el.id==='certificate-auto'){const key=el.id==='registration-auto'?'registration':'certificate';state.detail['generate_'+key]=el.checked;const input=$('[name='+key+']',$('#record-form'));if(input){if(el.checked){input.dataset.manualValue=input.value;input.value='';state.detail.fields[key]='';}else{input.value=input.dataset.manualValue||'';state.detail.fields[key]=input.value;}input.readOnly=el.checked;input.placeholder=el.checked?'Dibuat saat disimpan':'';}return;}const key={'filter-scheme':'scheme','filter-year':'year','filter-result':'result'}[el.id];if(key){state.filters[key]=el.value;state.page=1;renderRecordTable();}if(el.id==='master-category'){state.masterCategory=el.value;state.masterSearch='';state.masterPage=1;renderMasters(el.value);}if(el.id==='master-sort-select'){const [col,ord]=el.value.split('-');state.masterSort={column:col,order:ord};renderMasterTable();}if(el.dataset.row){if(el.checked)state.selected.add(Number(el.dataset.row));else state.selected.delete(Number(el.dataset.row));renderPreview();}if(el.id==='select-valid'){state.selected=el.checked?new Set(state.preview.rows.filter(r=>!r.errors.length).map(r=>r.number)):new Set();renderPreview();}});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button||button.disabled)return;const action=button.dataset.action;button.disabled=true;try{
 if(action==='reload')await route();
 else if(action==='new')await openDetail(0);
 else if(action==='registration-scheme'){state.filters={q:'',scheme:button.dataset.scheme,result:'',year:''};location.hash='records';}
 else if(action==='detail')await openDetail(button.dataset.id);
 else if(action==='close')$('#detail-dialog').close();
 else if(action==='detail-tab'){if(state.tab==='data'&&$('#record-form')&&isAdmin()){for(const [k,v]of new FormData($('#record-form')))state.detail.fields[k]=v;}state.tab=button.dataset.tab;renderDetail();}
 else if(action==='page'){state.page+=Number(button.dataset.delta);renderRecordTable();}
 else if(action==='preview-page'){state.previewPage+=Number(button.dataset.delta);renderPreview();}
 else if(action==='template')await download('/api/export?template=1');
 else if(action==='export')await download('/api/export?'+new URLSearchParams(state.filters));
 else if(action==='backup'){toast('Menyiapkan cadangan…');await download('/api/backup');toast('Cadangan tanpa data asesi berhasil diunduh.');}
 else if(action==='commit'){const result=await api('/api/import/commit',{method:'POST',body:{id:state.preview.id,rows:[...state.selected]}});state.preview=null;state.selected.clear();toast(`${result.imported} asesmen berhasil disimpan.`);location.hash='records';}
 else if(action==='view-doc'){const d=state.docs.find(d=>d.id===button.dataset.id);const path='/api/documents/'+d.id;const res=await fetch(path);if(!res.ok){const data=await res.json();throw new Error(data.error);}const blob=await res.blob();const url=URL.createObjectURL(blob);const el=$('#doc-viewer');if(el.dataset.blob)URL.revokeObjectURL(el.dataset.blob);el.dataset.blob=url;el.innerHTML=d.mime==='application/pdf'?`<iframe class="doc-viewer" title="Pratinjau scan" src="${url}"></iframe>`:`<img class="doc-viewer" alt="Scan ${esc(d.name)}" src="${url}">`;el.scrollIntoView({behavior:'smooth',block:'nearest'});}
 else if(action==='download-doc')await download('/api/documents/'+button.dataset.id+'?download=1');
 else if(['master-sort','master-page','edit-master','cancel-master','delete-master'].includes(action))await handleMasterAction(button);
}catch(e){toast(e.message,true);}finally{button.disabled=false;}});
document.addEventListener('submit',async event=>{const form=event.target;const formID=form.getAttribute('id');if(!formID)return;event.preventDefault();const button=$('button[type="submit"]',form);if(button?.disabled)return;if(button)button.disabled=true;const values=Object.fromEntries(new FormData(form));try{
 if(formID==='login-form'){$('#login-error').textContent='';state.user=await api('/api/login',{method:'POST',body:values});await start();form.reset();}
 else if(formID==='import-form'){state.preview=await api('/api/import/preview',{method:'POST',body:new FormData(form)});state.previewPage=1;state.selected=new Set(state.preview.rows.filter(r=>!r.errors.length).map(r=>r.number));renderPreview();$('#import-preview').scrollIntoView({behavior:'smooth'});}
 else if(formID==='record-form'){$('#record-error').textContent='';const r=state.detail;const merged={...r.fields,...values,education_label:'',occupation_label:''};const result=await api('/api/records',{method:'POST',body:{id:r.id,version:r.version,fields:merged,legacy_id:r.legacy_id||0,generate_registration:!!r.generate_registration,generate_certificate:!!r.generate_certificate}});state.all=await api('/api/records');state.detail=structuredClone(state.all.find(v=>v.id===result.id));renderDetail();toast('Data asesmen berhasil disimpan.');if(location.hash==='#registrations')await route();if(location.hash==='#records')renderRecords();else if(location.hash==='#dashboard'||!location.hash)renderDashboard();}
 else if(formID==='document-form'){await api(`/api/records/${state.detail.id}/documents`,{method:'POST',body:new FormData(form)});state.docs=await api(`/api/records/${state.detail.id}/documents`);state.all=await api('/api/records');renderDetail();toast('Scan berhasil tersimpan.');if(location.hash==='#records')renderRecords();else if(location.hash==='#dashboard'||!location.hash)renderDashboard();}
 else if(formID==='master-form')await submitMaster(form,values);
 else if(formID==='password-form'){await api('/api/password',{method:'POST',body:values});showLogin();toast('Kata sandi diperbarui. Silakan masuk kembali.');}
 else if(formID==='user-form'){await api('/api/users',{method:'POST',body:values});form.reset();toast('Akun pengguna berhasil dibuat.');}
}catch(e){const errorSelector={'login-form':'#login-error','record-form':'#record-error','master-form':'#master-error'}[formID];const errorElement=errorSelector&&$(errorSelector);if(errorElement)errorElement.textContent=e.message;else toast(e.message,true);}finally{if(button)button.disabled=false;}});
$('#logout').addEventListener('click',async()=>{try{await api('/api/logout',{method:'POST',body:{}});showLogin();}catch(e){toast(e.message,true);}});
window.addEventListener('hashchange',route);
$('#detail-dialog').addEventListener('close',releasePreviewImage);
api('/api/me').then(user=>{state.user=user;return start();}).catch(()=>showLogin());
