'use strict';
const legacyState={catalog:null,table:'skema',q:'',column:'',value:'',page:1,view:'data',data:null};
let legacyRequest=0;
const legacyLabels={activitylog:'Aktivitas lama',asesiprofile:'Profil asesi',asesmenmandiri:'Asesmen mandiri',banksoal:'Bank soal',certificatesequence:'Urutan sertifikat',elemenkompetensi:'Elemen kompetensi',kriteriaunjukkerja:'Kriteria unjuk kerja',legacyarchiveimport:'Catatan arsip lama',paketsoal:'Paket soal',paketsoalitem:'Isi paket soal',parameterbnsp:'Parameter BNSP',pendaftaran:'Pendaftaran',registrationsequence:'Urutan registrasi',skema:'Skema sertifikasi',unitkompetensi:'Unit kompetensi',user:'Pengguna lama'};
const legacyQuery=()=>new URLSearchParams({q:legacyState.q,column:legacyState.column,value:legacyState.value,page:String(legacyState.page)});
async function showRegisterWeb(){
 legacyState.catalog=await api('/api/registerweb');
 if(!legacyState.catalog.tables.length){$('#content').innerHTML=heading('Database RegisterWeb','Seluruh tabel sumber tersedia sebagai salinan lokal setelah migrasi.')+empty('Belum ada salinan RegisterWeb','Jalankan migrasi MySQL dari panduan proyek untuk memuat struktur dan data tabel.');return;}
 if(!legacyState.catalog.tables.some(t=>t.name===legacyState.table))legacyState.table=legacyState.catalog.tables[0].name;
 await loadLegacyTable();
}
async function loadLegacyTable(){
 const serial=++legacyRequest;
 const result=await api('/api/registerweb/'+encodeURIComponent(legacyState.table)+'?'+legacyQuery());
 if(serial!==legacyRequest||location.hash!=='#registerweb')return;
 legacyState.data=result;legacyState.page=result.page;renderLegacy();
}
function renderLegacy(){
 const c=legacyState.catalog,d=legacyState.data,t=d.table;
 const total=c.tables.reduce((sum,t)=>sum+t.count,0);
 $('#content').innerHTML=heading('Database RegisterWeb','Telusuri salinan tabel, isi data, struktur kolom, dan relasi dari proyek sebelumnya.','<button data-legacy-action="export">↓ Ekspor tabel ini</button>')+
 `<div class="stats"><div class="stat"><div class="stat-top">Tabel tersalin<span class="stat-icon">▦</span></div><strong>${c.tables.length}</strong><small>Termasuk tabel kosong</small></div><div class="stat"><div class="stat-top">Baris tersalin<span class="stat-icon">▤</span></div><strong>${number(total)}</strong><small>Isi diverifikasi dengan checksum</small></div><div class="stat"><div class="stat-top">Kolom tersedia<span class="stat-icon">▥</span></div><strong>${c.tables.reduce((sum,t)=>sum+t.columns.length,0)}</strong><small>Tipe, default, indeks, dan nullable</small></div><div class="stat"><div class="stat-top">Database tujuan<span class="stat-icon">◫</span></div><strong class="database-name">lspfi_dms</strong><small>Tabel sumber: ${esc(c.source)}</small></div></div>`+
 `<div class="info-box"><strong>Salinan mandiri dari RegisterWeb</strong>Disalin ${esc(new Date(c.created).toLocaleString('id-ID'))}. ${c.scope==='references-without-asesi'?'Salinan ini dipulihkan dari backup referensi; isi tabel dan akun asesi dikecualikan.':'Tabel berawalan rw_ mempertahankan seluruh data dan struktur sumber.'} Halaman ini hanya membaca salinan lokal; perubahan pada proyek lama tidak tersinkron otomatis. Kata sandi disembunyikan. Dokumen MongoDB belum termasuk.</div>`+
 `${c.orphans?.length?`<div class="info-box"><strong>Relasi sumber yang perlu ditinjau</strong>${c.orphans.map(o=>`${esc(o.table)}.${o.columns.map(esc).join(', ')} → ${esc(o.target)}: ${o.count} baris tanpa data induk`).join('<br>')}<br>Baris tersebut tetap dipertahankan sesuai sumber; tidak diperbaiki otomatis.</div>`:''}`+
 `<section class="panel"><div class="toolbar"><label class="legacy-select">Tabel<select id="legacy-table">${c.tables.map(table=>`<option value="${esc(table.name)}" ${table.name===t.name?'selected':''}>${esc(legacyLabels[table.name]||table.name)} · ${table.count} baris</option>`).join('')}</select></label><form data-legacy-search class="legacy-search"><input name="q" aria-label="Cari isi tabel" placeholder="Cari pada isi tabel ini…" value="${esc(legacyState.q)}"><button type="submit">Cari</button></form></div><div class="tabs"><button data-legacy-action="view" data-view="data" class="${legacyState.view==='data'?'active':''}">Isi data (${d.total})</button><button data-legacy-action="view" data-view="structure" class="${legacyState.view==='structure'?'active':''}">Struktur & relasi</button></div>${legacyState.column?`<div class="summary-bar"><span>Filter relasi: ${esc(legacyState.column)} = ${esc(legacyState.value)}</span><button data-legacy-action="reset-filter">Hapus filter</button></div>`:''}${legacyState.view==='structure'?legacyStructure(t):legacyGrid(d)}</section>`;
}
function legacyGrid(d){
 const cols=d.table.columns.filter(c=>!/password|secret|token/i.test(c.name));
 const table=d.rows.length?`<div class="table-wrap legacy-table"><table><thead><tr><th>Detail</th>${cols.map(c=>`<th>${esc(c.name)}</th>`).join('')}</tr></thead><tbody>${d.rows.map((row,i)=>`<tr><td><button data-legacy-action="detail" data-index="${i}" class="row-button">Lihat ↗</button></td>${cols.map(c=>{const value=row[c.name];return `<td class="legacy-cell" title="${esc(value??'NULL')}">${value===null?'<span class="muted">NULL</span>':esc(value?.length>100?value.slice(0,100)+'…':value)}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`:empty('Tidak ada baris untuk ditampilkan','Tabel ini kosong atau tidak ada data yang cocok dengan pencarian. Struktur tabel tetap tersedia.');
 const pages=Math.max(1,Math.ceil(d.total/d.page_size));return table+`<div class="pagination"><span>${number(d.total)} baris · ${esc(d.table.target)}</span><div class="actions"><span>${d.page} / ${pages}</span><button data-legacy-action="page" data-delta="-1" ${d.page<=1?'disabled':''}>←</button><button data-legacy-action="page" data-delta="1" ${d.page>=pages?'disabled':''}>→</button></div></div>`;
}
function legacyStructure(t){return `<div class="panel-body"><p class="helper">Nama tabel: <strong>${esc(t.target)}</strong> · Engine: ${esc(t.engine)} · ${t.columns.length} kolom. Foreign key ditampilkan sesuai database aktual.</p><div class="table-wrap"><table><thead><tr><th>Kolom</th><th>Tipe</th><th>Boleh kosong</th><th>Default</th><th>Tambahan</th></tr></thead><tbody>${t.columns.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.type)}</td><td>${c.nullable?'Ya':'Tidak'}</td><td>${esc(c.default??'NULL')}</td><td>${esc(c.extra||'—')}</td></tr>`).join('')}</tbody></table></div><h3 class="section-label">INDEKS</h3><div class="table-wrap"><table><thead><tr><th>Nama indeks</th><th>Kolom</th><th>Urutan</th><th>Unik</th></tr></thead><tbody>${t.indexes.map(i=>`<tr><td>${esc(i.name)}</td><td>${esc(i.column)}</td><td>${i.position}</td><td>${i.unique?'Ya':'Tidak'}</td></tr>`).join('')}</tbody></table></div><h3 class="section-label">RELASI FOREIGN KEY</h3>${t.relations.length?`<ul class="plain-list">${t.relations.map(r=>`<li>${esc(r.column)} → ${esc(r.table)}.${esc(r.target_column)} · ON DELETE ${esc(r.on_delete)} · ON UPDATE ${esc(r.on_update)}</li>`).join('')}</ul>`:'<p class="helper">Tidak ada foreign key yang didefinisikan pada tabel sumber ini. Hubungan logis di kode aplikasi lama tidak otomatis menjadi foreign key.</p>'}<details><summary class="helper">Lihat perintah struktur asli (SQL)</summary><pre class="legacy-ddl">${esc(t.ddl)}</pre></details></div>`;}
function legacyRecord(index){
 const d=legacyState.data,row=d.rows[index],t=d.table;
 const relations=[];
 for(const r of t.relations){if(row[r.column]!==null&&row[r.column]!==undefined)relations.push({label:`${r.column} → ${legacyLabels[r.table]||r.table}`,table:r.table,column:r.target_column,value:row[r.column]});}
 for(const other of legacyState.catalog.tables){for(const r of other.relations){if(r.table===t.name&&row[r.target_column]!==null&&row[r.target_column]!==undefined)relations.push({label:`${legacyLabels[other.name]||other.name} yang terhubung`,table:other.name,column:r.column,value:row[r.target_column]});}}
 $('#detail-content').innerHTML=`<div class="dialog-top"><div><h2>${esc(legacyLabels[t.name]||t.name)} · ${esc(row.id||'Detail')}</h2><p>${esc(t.target)} · salinan lokal RegisterWeb</p></div><button data-action="close" aria-label="Tutup detail">✕</button></div><div class="dialog-body">${t.name==='pendaftaran'?`<div class="info-box"><strong>Gunakan riwayat ini di ruang arsip</strong>Periksa data hasil pemetaan sebelum menyimpan. Setelah menjadi arsip, Anda dapat menambahkan scan dan mengekspor Data Induk.</div><button class="primary legacy-relations" data-legacy-action="adopt" data-id="${esc(row.id)}">Gunakan di Data Asesmen →</button>`:''}${relations.length?`<div class="actions legacy-relations">${relations.map(r=>`<button data-legacy-action="relation" data-table="${esc(r.table)}" data-column="${esc(r.column)}" data-value="${esc(r.value)}">${esc(r.label)} →</button>`).join('')}</div>`:''}<dl class="legacy-detail">${t.columns.map(c=>`<div><dt>${esc(c.name)} <small>${esc(c.type)}</small></dt><dd>${esc(row[c.name]??'NULL')}</dd></div>`).join('')}</dl></div>`;
 $('#detail-dialog').showModal();
}
document.addEventListener('change',async e=>{if(e.target.id!=='legacy-table')return;legacyState.table=e.target.value;legacyState.page=1;legacyState.q='';legacyState.column='';legacyState.value='';try{await loadLegacyTable();}catch(error){toast(error.message,true);}});
document.addEventListener('click',async e=>{const button=e.target.closest('[data-legacy-action="adopt"]');if(!button)return;try{const candidate=await api('/api/registerweb/pendaftaran/'+encodeURIComponent(button.dataset.id)+'/candidate');if(candidate.id){state.all=await api('/api/records');$('#detail-dialog').close();await openDetail(candidate.id);}else{state.detail=candidate;state.docs=[];state.tab='data';renderDetail();}}catch(error){toast(error.message,true);}});
document.addEventListener('submit',async e=>{if(!e.target.matches('[data-legacy-search]'))return;e.preventDefault();legacyState.q=new FormData(e.target).get('q');legacyState.page=1;try{await loadLegacyTable();}catch(error){toast(error.message,true);}});
document.addEventListener('click',async e=>{const button=e.target.closest('[data-legacy-action]');if(!button||button.disabled)return;button.disabled=true;try{switch(button.dataset.legacyAction){case 'view':legacyState.view=button.dataset.view;renderLegacy();break;case 'page':legacyState.page+=Number(button.dataset.delta);await loadLegacyTable();break;case 'detail':legacyRecord(Number(button.dataset.index));break;case 'export':await download('/api/registerweb/'+encodeURIComponent(legacyState.table)+'/export?'+legacyQuery());break;case 'reset-filter':legacyState.column='';legacyState.value='';legacyState.page=1;await loadLegacyTable();break;case 'relation':legacyState.table=button.dataset.table;legacyState.column=button.dataset.column;legacyState.value=button.dataset.value;legacyState.q='';legacyState.page=1;legacyState.view='data';$('#detail-dialog').close();await loadLegacyTable();break;}}catch(error){toast(error.message,true);}finally{button.disabled=false;}});
